### ISSUE TITLE
annotation improvement idea

### ISSUE THREAD

**Issue by Sarcasm** [sebastiencs/company-box#1]
To follow up on the comment here:

> > Great work anyway, I do think the annotation could use some work, but that's just a matter of taste.
>
> Thanks. What kind of work ? Any ideas for improvement is more than welcome :)
> -- https://github.com/company-mode/company-mode/issues/756#issuecomment-374408532

Right now, from the README screenshot we see the following candidates:

```
[f] SUB_CHAR_TABLE_P            bool SUB_CHAR_TABLE_P(Lisp_Object a)
[v] Qchar_or_string_p           const Lisp_Object Qchar_or_string_p
```

Removing the unnecessary repetition of the identifier, we can have:

```
[f] SUB_CHAR_TABLE_P(Lisp_Object a) -> bool
[v] Qchar_or_string_p : const Lisp_Object
```

And if a field, is a member of a class (in C++),
the right column could hold the "parent context":

```
[f] append(const char *str) -> std::string              std::string
[f] empty() const -> bool                               std::string
```

**Comment by dgutov** [comment]
Isn't that up to the backend?

**Comment by sebastiencs** [comment]
Yes the annotation is formatted by the backend, there is not much I can do in this case :/

**Comment by Sarcasm** [comment]
Indeed, the issue is not on the right project, sorry about that.
