### ISSUE TITLE
Automatically disable line numbers

### ISSUE THREAD

**Issue by noctuid** [sebastiencs/company-box#10]
It would be nice if this package (possibly optionally) automatically set `display-line-numbers` to nil in its buffers.

**Comment by sebastiencs** [comment]
Do you mean `display-line-numbers-mode` is enabled in the child frame with all the completions candidates ?

**Comment by sebastiencs** [comment]
https://github.com/sebastiencs/company-box/commit/2f55d5a893e4a05bd7a62711c5cc879c98725f52 set `display-line-numbers` to nil

**Comment by noctuid** [comment]
Thanks!
