### ISSUE TITLE
Setting "company-selection-wrap-around" with company-box-mode enabled has no effect. 

### ISSUE THREAD

**Issue by FilipCon** [sebastiencs/company-box#100]
I figured that the "company-selection-wrap-around" functionality from company-mode does no longer work when company-box-mode is enabled. In solely company-mode it works fine. Tested with Emacs 27 with native json. I can't seem to find any reference to this, whether its an issue or unsupported feature. Although it not a major problem, sometimes it gets annoying to scroll all the way up! :D

**Comment by larebsyed** [comment]
#102
