### ISSUE TITLE
Icons are not showing for not focused items

### ISSUE THREAD

**Issue by kiennq** [sebastiencs/company-box#105]
It seems that c88b220975c3eafe60096b9 breaks this.
Here is what I get now:
![image](https://user-images.githubusercontent.com/2631472/89398948-bdcc7180-d74c-11ea-9dcf-313a4554dbb1.png)

**Comment by stardiviner** [comment]
I got similar problem, except that all icons not shown on my machine. I'm using MELPA version `20200810.557`. But I use the latest Git "master" branch works fine. Currently latest commit is `439951e master upstream/master Add space when numbers are on the right`.

**Comment by sebastiencs** [comment]
@kiennq Does it still occurs ? https://github.com/sebastiencs/company-box/commit/20384f0e382c063173b9d863344b1b23bc1e4954 might have fix this

**Comment by kiennq** [comment]
Yeah, it's fixed by your commit.
