### ISSUE TITLE
Incompatibilty with company-yasnippet

### ISSUE THREAD

**Issue by ludvikn** [sebastiencs/company-box#108]
Using `company-box` is messing with `company-yasnippet`. Typing and selecting using `company-yasnippet` still works in the sense that I can blindly select a snippet, but no text or completion popup appears between using `company-yasnippet` and selecting a snippet.

My configs:
```
(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay 0)
  (company-minimum-prefix-length 1)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (company-wrap-around 't)
  (global-company-mode t))

(use-package company-box
  :after company
  :diminish
  :hook (company-mode . company-box-mode))
```

**Comment by sebastiencs** [comment]
Hello @ludvikn, I'm also using `company-yasnippet` but it works correctly.
Do you have any errors in the `*messages*` buffer ?

**Comment by ludvikn** [comment]
I clicked around a bit. And seems like it is working correctly. The issue appears to occur only when I have a single snippet loaded. After I added a second one, the popup works.
