### ISSUE TITLE
Invalid byte opcode: op=0, ptr=6

### ISSUE THREAD

**Issue by dwuggh** [sebastiencs/company-box#109]
## description
- after update, company-box throws `error: Invalid byte opcode: op=0, ptr=6` when using company
- It works fine before, I installed company-box on July 20.
- Both native-compiled and byte-compiled company-box not work.
- I've tried recomplie company-box, but didn't work.
## environment
- system: manjaro linux x86-64
- emacs: 28.0.50 native-comp branch(gccemacs)
- company-box version: 981aa41

backtrace:
```
Debugger entered--Lisp error: (error "Invalid byte opcode: op=0, ptr=6")
  company-box--scrollbar-prevent-changes()
  redisplay_internal\ \(C\ function\)()
```

**Comment by bjcohen** [comment]
Seeing the same error on OS X 10.15.4 on Emacs 28.0.50 and company-box 981aa41.

**Comment by sebastiencs** [comment]
Thanks, should be fixed with https://github.com/sebastiencs/company-box/commit/6eb8820787b7a0363ead906d8a23139ca8fd5eee

**Comment by dwuggh** [comment]
Thanks! It works for me.
