### ISSUE TITLE
Old child frame doesn't go away

### ISSUE THREAD

**Issue by noctuid** [sebastiencs/company-box#11]
For example, when exiting org src mode with an active popup, it doesn't go away. The same thing happens if I kill the buffer with an active popup or switch to another window. It sticks around until the next completion popup.

**Comment by sebastiencs** [comment]
Displaying and hiding the frame is managed by `company-mode`, I've also noticed that sometimes the frame is still there when another window is selected or the current one display another buffer.
@dgutov any thoughts on this ? I think it should be fixed in `company-mode`?

**Comment by dgutov** [comment]
Fixed how? Please describe exactly how company-mode might be at fault.

**Comment by sebastiencs** [comment]
@dgutov By not sending the `hide` command in those cases

**Comment by sebastiencs** [comment]
@noctuid Can you test the changes in https://github.com/sebastiencs/company-box/commit/afb7a2936dc162120dba9f161ab6ad564c53a454 ?
