### ISSUE TITLE
Popup disappearing when there is only one candidate left

### ISSUE THREAD

**Issue by ludvikn** [sebastiencs/company-box#110]
These are my company configs:

(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay 0)
  (company-minimum-prefix-length 1)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (company-wrap-around 't)
  (global-company-mode t))

(use-package company-box
  :after company
  :diminish
  :hook (company-mode . company-box-mode))

**Comment by sebastiencs** [comment]
You can change that behavior with `(setq company-box-show-single-candidate t)`
