### ISSUE TITLE
company-common face has one more char colorized in selected candidate

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#112]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/378699/90348226-9ee0b000-e067-11ea-9424-6c8e9ef9b358.png)

You can see I selected the second candidate, it the company-common face also highlighted one more extra face "-a" part.

**Comment by sebastiencs** [comment]
Thanks @stardiviner I will take a look

**Comment by sebastiencs** [comment]
@stardiviner Should be fixed with https://github.com/sebastiencs/company-box/issues/112

**Comment by stardiviner** [comment]
Yes, fixed the issues, I confirmed with latest pull. Thanks @sebastiencs  :+1:
