### ISSUE TITLE
Doc delay at the first candidate

### ISSUE THREAD

**Issue by seagle0128** [sebastiencs/company-box#114]
`run-with-idle-timer` causes the delay of displaying doc at the first candidate. It works after moving up or down.
I test with `run-with-timer`, and it seems working but I am not sure if there is side-effect.

https://github.com/sebastiencs/company-box/blob/20384f0e382c063173b9d863344b1b23bc1e4954/company-box-doc.el#L137

**Comment by sebastiencs** [comment]
Hi @seagle0128.

I'm not sure if I understand your issue, could you elaborate a bit ?

**Comment by seagle0128** [comment]
> Hi @seagle0128.
> 
> I'm not sure if I understand your issue, could you elaborate a bit ?

Sorrt for the confusion. When comoany-box displaying the candidates, the doc of the first candidate will be delayed 5 seconds to display although the it's set to 0.5s. The docs are displayed timely if moving up or down to select other candidates.

**Comment by stardiviner** [comment]
I can reproduce this problem. I've noticed this problem before.

**Comment by seagle0128** [comment]
@stardiviner so, can u pls try this snippet and check if there is any side-effect?

```elisp
(defun company-box-doc (selection frame)
          (when company-box-doc-enable
            (-some-> (frame-parameter frame 'company-box-doc-frame)
              (make-frame-invisible))
            (when (timerp company-box-doc--timer)
              (cancel-timer company-box-doc--timer))
            (setq company-box-doc--timer
                  (run-with-timer
                   company-box-doc-delay nil
                   (lambda nil
                     (company-box-doc--show selection frame)
                     (company-ensure-emulation-alist))))))
```

**Comment by stardiviner** [comment]
Now the doc popup faster, feels same fast as other candidates on first candidate. Confirmed. Thanks for solution.

**Comment by sebastiencs** [comment]
Thanks for testing @stardiviner @seagle0128. I will use `run-with-timer`

**Comment by seagle0128** [comment]
Cool~~~ Thank you! @sebastiencs

**Comment by seagle0128** [comment]
@sebastiencs Any update?

**Comment by sebastiencs** [comment]
@seagle0128 Done

**Comment by seagle0128** [comment]
@sebastiencs  Thank you! It does work.
