### ISSUE TITLE
Material icon vertically misaligned regardless of v-adjust

### ISSUE THREAD

**Issue by angrybacon** [sebastiencs/company-box#116]
The issue is independent of font size and family for my `default` face but I get different results with other font families in `all-the-icons`. I've put a screenshot of the issue, hopefully more visible with the highlighted face.

The `all-the-icons` call seems fine with an adjusted value of `v-adjust`. But setting up the same icon with the same values within `company-box`, icons are always at the top-most position.

![image](https://user-images.githubusercontent.com/5608624/90705894-42160d00-e294-11ea-8d71-891bd14dd300.png)

This is what `company-box-icons-all-the-icons`'s value looks like in a `*Help*` buffer from `describe-variable`.

![image](https://user-images.githubusercontent.com/5608624/90706471-78a05780-e295-11ea-923e-ddb2e47b75f8.png)

And this is how I setup `company-box`:

```elisp
;;; -*- lexical-binding: t -*-

(use-package company-box
  :after company
  :hook
  (company-mode . company-box-mode)
  :custom
  (company-box-icons-alist 'company-box-icons-all-the-icons)
  (company-box-icons-all-the-icons
   (let ((all-the-icons-default-adjust -.15)
         (all-the-icons-scale-factor .8)
         (red 'all-the-icons-red))
     `(...
       (Variable . ,(all-the-icons-material "adjust" :face red))
       ...)))
  (company-box-scrollbar nil)
  (company-box-show-single-candidate nil))
```

**Comment by sebastiencs** [comment]
Thanks for reporting this @angrybacon.
I know what is causing this issue I will fix it

**Comment by sebastiencs** [comment]
@angrybacon It should be fixed with https://github.com/sebastiencs/company-box/commit/d8f71fde7a3301a62f9f6f627aa51610a294f4df, can you confirm ?

**Comment by angrybacon** [comment]
@sebastiencs Thanks, looks like that fixed it 👍
