### ISSUE TITLE
Latest update MELPA caused multiple company-box tooltip frames

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#121]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/378699/91110649-0b376100-e6b1-11ea-8182-089a1472dbc6.png)

MELPA version: `20200824.948`

**Comment by sebastiencs** [comment]
Is there a way to reproduce this ?

Are you sure it's on the melpa version ?
I remember having this bug while working on https://github.com/sebastiencs/company-box/pull/119 branch, but even on that branch I think I fixed it.
I never saw this on the master branch.

I tried the melpa version and I can't reproduce

**Comment by stardiviner** [comment]
Weird, I restart Emacs, the problem is gone. Sorry for distribution. ;)
