### ISSUE TITLE
company-box does not obey `completion-ignore-case`

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#122]
In company-mode, if I set `completion-ignore-case` to `t`. I can complete Clojure code `(java.lang.System)` through input `(java.lang.sys)`. After enabled `company-box-mode`. This does not work now.

Here is the related issue link https://github.com/clojure-emacs/cider/issues/2895

**Comment by stardiviner** [comment]
After debug in `company-box`, I found the bellowing code caused the problem.
```elisp
(setq company-frontends (->> (delq 'company-pseudo-tooltip-frontend company-frontends)
                             (delq 'company-pseudo-tooltip-unless-just-one-frontend)))
```

**Comment by stardiviner** [comment]
Seems `company-box-front` does not work like `company-pseudo-tooltip-frontend`.

**Comment by sebastiencs** [comment]
Hello @stardiviner, I don't understand the issue.
The completion itself is handled by `company-mode`, `company-box` just display the result.
Can you explain a bit more ?

**Comment by stardiviner** [comment]
@sebastiencs Sorry for my mass messages. ;)

In Clojure code, when I input `(java.lang.sys`, It should get completion candidates `(java.lang.System`. But when I have `company-box-mode` enabled, it does not display this candidate. When I disable `company-box-mode`, it displays the candidate.

My mistake, I realized the bellowing code in `company-box` removed some frontends. But `company-pseudo-tooltip-frontend` can support display the candidate `(java.lang.System`.
```
(setq company-frontends (->> (delq 'company-pseudo-tooltip-frontend company-frontends)
                             (delq 'company-pseudo-tooltip-unless-just-one-frontend)))
```

**Comment by stardiviner** [comment]
Here is a GIF I recorded for demostration.

![output](https://user-images.githubusercontent.com/378699/91272456-54210f80-e7ae-11ea-9bb9-a8d83c20d254.gif)

**Comment by sebastiencs** [comment]
@stardiviner Does it work if you set `company-box-show-single-candidate` to `t`

**Comment by stardiviner** [comment]
It worked. Ahaha, that's great!, thanks @sebastiencs

**Comment by stardiviner** [comment]
I have a similar question, with input `(java.lang.System/getp`, I can't complete candidates like `(java.lang.System/getProperty`?
