### ISSUE TITLE
Company: frontend company-box-frontend error

### ISSUE THREAD

**Issue by seagle0128** [sebastiencs/company-box#123]
I got this error today after upgrading the package. No backtrace, no messages, no logs.

- Emacs 27.1
- company-box-20200828.1627

```elisp
Company: frontend company-box-frontend error "Invalid alignment size -3, aborting" on command update
```

**Comment by sebastiencs** [comment]
@seagle0128 Thanks for reporting this.

Can you do:
```
[M-x] toggle-debug-on-error
```
And reproduce the error ? It will show a backtrace

**Comment by seagle0128** [comment]
Already turn on it, but no backtrace.
Disable company-box-mode, the issue disappears.

**Comment by seagle0128** [comment]
@sebastiencs I think I found the root cause. If `(setq company-box-highlight-prefix t)`, the issue occurs.

**Comment by sebastiencs** [comment]
Should be fixed with https://github.com/sebastiencs/company-box/commit/adcb52b71f447e27493c4c98ad1d1711639f6e10

**Comment by seagle0128** [comment]
Confirm. It's fixed.
