### ISSUE TITLE
First char is missing

### ISSUE THREAD

**Issue by allenryb** [sebastiencs/company-box#126]
The first character of the first word in a line is missing in the first candidate of company-box.
For example, the first company candidate of `use` will be listed as `se` and the number "1" is missed:
![companybox2](https://user-images.githubusercontent.com/6965371/91933127-bd5ad280-ed1a-11ea-9b35-da82b7dca180.png)
This problem only appear at the first word of a line.

Although the completion is right, it's annoying.
May I ask how to fix this?
My emacs version: 27.1
Operating system: Ubuntu 20.04

**Comment by sebastiencs** [comment]
Hello @allenryb, does it always occurs or under certain conditions ?
If you are scrolling the list of candidates, does it still occurs with the 1st line ?

Could you send your configuration for `company-box` ? Or if your full configuration is public maybe send a link to it ?

**Comment by allenryb** [comment]
It always occurs. 
If I scroll the list of candidates, it still occurs.
Moreover if I scroll back, the previous candidates will miss the fisrt character.

![companybox](https://user-images.githubusercontent.com/6965371/92197252-d347cf00-eea3-11ea-8a57-ee97e1fbc411.gif)

My configuration about `company-mode` and `company-box` is 
```
(use-package company 
  :ensure t
  :diminish company-mode
  :config
  (add-hook 'after-init-hook 'global-company-mode)
  (setq company-show-numbers t)
  (setq company-dabbrev-downcase nil) 
  (setq company-dabbrev-ignore-case nil)
  (setq company-idle-delay 0))

(use-package company-box
  :ensure t
  :hook (company-mode . company-box-mode)
  :init
  (setq company-box-doc-enable nil))
```

**Comment by sebastiencs** [comment]
@allenryb https://github.com/sebastiencs/company-box/commit/4265eaf9e4d29f8b93e125fa807e2085e8e0ea3b should fix your issue. Can you please confirm

**Comment by allenryb** [comment]
It's fixed. Thanks!
