### ISSUE TITLE
error-messages after updating company

### ISSUE THREAD

**Issue by phisu** [sebastiencs/company-box#127]
i updated 
company-box to 20200904.533
company-lsp to 20190612.1553
company-prescient to 20200716.1414

and now i get frequently the following error-message:

Company: An error occurred in auto-begin
Company: frontend company-box-frontend error "Wrong number of arguments: ((t) (string) (let ((selection company-selection) (common (or company-common company-prefix))) (save-current-buffer (set-buffer (company-box--get-buffer)) (erase-buffer) (insert string "
") (setq mode-line-format nil display-line-numbers nil truncate-lines t cursor-in-non-selected-windows nil) (set (make-local-variable (quote scroll-step)) 1) (set (make-local-variable (quote scroll-conservatively)) 10000) (set (make-local-variable (quote scroll-margin)) 0) (set (make-local-variable (quote scroll-preserve-screen-position)) t) (add-hook (quote window-configuration-change-hook) (quote company-box--prevent-changes) t t) (company-box--update-line selection common)))), 2" on command show

**Comment by sebastiencs** [comment]
Hello @phisu ,

Please run `M-x` `toggle-debug-on-error` and reproduce the bug, a backtrace will appears, can you post it here.

What emacs version are you using ?

Can you try to recompile `company-box` (`M-:`)
```
 (byte-recompile-directory (file-name-directory (find-library-name "company-box")) 0 t)
```

Can you send your configuration for `company-box` and `company`

**Comment by phisu** [comment]
the backtrace:

Debugger entered--entering a function:
* error-message-string((wrong-number-of-arguments ((t) (string) (let ((selection company-selection) (common (or company-common company-prefix))) (save-current-buffer (set-buffer (company-box--get-buffer)) (erase-buffer) (insert string "\n") (setq mode-line-format nil display-line-numbers nil truncate-lines t cursor-in-non-selected-windows nil) (set (make-local-variable (quote scroll-step)) 1) (set (make-local-variable (quote scroll-conservatively)) 10000) (set (make-local-variable (quote scroll-margin)) 0) (set (make-local-variable (quote scroll-preserve-screen-position)) t) (add-hook (quote window-configuration-change-hook) (quote company-box--prevent-changes) t t) (company-box--update-line selection common)))) 2))
  company-call-frontends(show)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer importProjekte.php> #<window 3 on importProjekte.php> 16286 33900)
  apply(company-idle-begin (#<buffer importProjekte.php> #<window 3 on importProjekte.php> 16286 33900))
  timer-event-handler([t 24404 57508 80159 nil company-idle-begin (#<buffer importProjekte.php> #<window 3 on importProjekte.php> 16286 33900) nil 38999])
  read-event(nil t 3)
  sit-for(3)
  flyspell-check-word-p()
  flyspell-post-command-hook()

my emacs version:

GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian

i am using the centaur emacs configuration framework: 
https://github.com/seagle0128/.emacs.d

**Comment by sebastiencs** [comment]
@phisu Please make sure that your configuration is updated with the latest centaur.
centaur used to redefine functions that were modified recently in `company-box`

https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-company.el

**Comment by phisu** [comment]
i just updated centaur. but the issue still persists.

**Comment by sebastiencs** [comment]
You most likely have a compiled file of an old version of centaur somewhere (a file ending with `.elc`).

It is that version of `my-company-box--render-buffer` causing your issue. https://github.com/seagle0128/.emacs.d/commit/91e08439d62cedfce9da8fe9a8b833a29ad0dd04#diff-18a577e3c1bb530313fb7f98374df956

@seagle0128 is there any command that needs to be run to update @phisu's compiled files ?

**Comment by seagle0128** [comment]
`centaur-update` should work. If not, delete company-box and reinstall it.

**Comment by sebastiencs** [comment]
@phisu In addition to @seagle0128 instructions, please check that you don't have a file named `init-company.elc` somewhere

**Comment by phisu** [comment]
thank you for your help. i did not found init-company.elc in my .emacs.d directory. but i found init-company.el. this one was older than what you mentioned above in seagle0128/.emacs.d@91e0843#diff-18a577e3c1bb530313fb7f98374df956 . i copied https://github.com/seagle0128/.emacs.d/blob/91e08439d62cedfce9da8fe9a8b833a29ad0dd04/lisp/init-company.el over my init-company.el. the error message did not exist anymore. 
aftter that i did centaur-update and i could see that the files in  company-box-20200907.1454 was updated. 
no error messages any more. 
many thanks for your quick help.
