### ISSUE TITLE
Completion box are very small

### ISSUE THREAD

**Issue by azzamsa** [sebastiencs/company-box#129]
I stop using company-box for a year, but after (https://github.com/sebastiencs/company-box/issues/88, and https://github.com/sebastiencs/company-box/issues/54) I start using it again, it has been couple of months now.

Yesterday, I tray to do `straight-pull-all` which pull all new revision from my packages. Suddenly I have this broken state of company-box.

*the box are shrinked, very small*, I can't barely see it. Everything works after disabling company-box.

![Peek 2020-09-13 05-32](https://user-images.githubusercontent.com/17734314/93006179-542d5780-f583-11ea-8920-f96ba3f453d2.gif)

---

Should we have test for company-box, so any incoming changes doesn't break the current state?

related:

https://github.com/sebastiencs/company-box/issues/70

**Comment by sebastiencs** [comment]
Hello @azzamsa, most of the times this kind of issue is caused by another package.
I found your configuration https://github.com/azzamsa/emacs.d and tested it, but I couldn't reproduce the behavior on the gif.

Can you try to recompile `company-box`:
```
(byte-recompile-directory (file-name-directory (find-library-name "company-box")) 0 t)
```

Is there any messages in the `*messages*` buffer ?

> Should we have test for company-box, so any incoming changes doesn't break the current state?

That would be great, any help in the area is more than welcome

**Comment by azzamsa** [comment]
> Hello @azzamsa, most of the times this kind of issue is caused by another package.
> I found your configuration [azzamsa/emacs.d](https://github.com/azzamsa/emacs.d) and tested it, but I couldn't reproduce the behavior on the gif.

I have pushed my latest changes. I have some commits that not pushed.

----

![Peek 2020-09-14 05-54](https://user-images.githubusercontent.com/17734314/93030651-d6368280-f64e-11ea-9899-da13b82b5a77.gif)

After restating my Emacs, it appears to be fixed. Strange. I've tried to restart it multiple times yesterday.

I will reopen if the issue persists.

**Comment by sebastiencs** [comment]
> I will reopen if the issue persists.

@azzamsa Please do. I have pushed some changes to not make the buffer blink with dimmer-mode

**Comment by azzamsa** [comment]
> @azzamsa Please do. I have pushed some changes to not make the buffer blink with dimmer-mode, I observed this with your config

![Peek 2020-09-15 09-03](https://user-images.githubusercontent.com/17734314/93156429-541f8a00-f732-11ea-80d5-986744f9d82e.gif)

Works great!

**Comment by azzamsa** [comment]
Thanks a lot for company box. Really appreciate. :tada:
