### ISSUE TITLE
company-box-doc position does not handle vertical window split

### ISSUE THREAD

**Issue by fuxialexander** [sebastiencs/company-box#13]
![image](https://user-images.githubusercontent.com/8258908/39110263-1274a5fe-4703-11e8-8194-6d1f0dd2d72e.png)

**Comment by sebastiencs** [comment]
Thanks, fixed in https://github.com/sebastiencs/company-box/commit/538e88c3ee5fc783fec2241a6730d0f843acd016

**Comment by sebastiencs** [comment]
@fuxialexander I see that you're adding a space after your icons:
```el
(setq company-box-icons-elisp (list (concat (all-the-icons-material "functions") " ")))
```
Why ? It shouldn't be necessary, unless there is a bug. Is the result different if you don't add that space ?

**Comment by fuxialexander** [comment]
@sebastiencs yes that's old code. I already removed that. Originally thought I need to specifically add the padding

**Comment by sebastiencs** [comment]
Alright, I'm closing the issue
