### ISSUE TITLE
error messages Wrong number of arguments

### ISSUE THREAD

**Issue by phisu** [sebastiencs/company-box#130]
i updated to company-box-20200914.1015
and to emacs 27.1.

now i get frequently following error-message:

Company: An error occurred in auto-begin
Company: frontend company-box-frontend error "Wrong number of arguments: ((t) (candidate) (concat (and company-prefix (propertize company-prefix 'face 'company-tooltip-common)) (substring (propertize candidate 'face 'company-box-candidate) (length company-prefix) nil))), 2" on command show

**Comment by sebastiencs** [comment]
@phisu What is your configuration for `company-box` ? It looks like you have declared a function overriding the original one.

The face `company-box-candidate` is not used anymore so it's an old code.

**Comment by phisu** [comment]
i am using the cetaur configration framwork

**Comment by sebastiencs** [comment]
This is similar to https://github.com/sebastiencs/company-box/issues/127, you have an old version of a centaur config file somewhere
