### ISSUE TITLE
You need an evil-company-box-state

### ISSUE THREAD

**Issue by Alexander-Miller** [sebastiencs/company-box#14]
Same reason I need my own treemacs-evil. Setting a cursor-type won't do since evil is managing your cursor. You need to define a proper evil state and activate it in the company-box buffer. 

I can make the necessary changes, just let me know if you want this to be part of the main package (so as to avoid the awkward not-really dependency on evil) or if it should go into its own file and package.

**Comment by sebastiencs** [comment]
> I can make the necessary changes, just let me know if you want this to be part of the main package

That would be great, I think it should stay in the package.

> You need to define a proper evil state and activate it in the company-box buffer.

The company-box buffer and its frame are never selected, commands are executed "remotely" from the current buffer. So I'm not sure if you're right about that, but since I know nothing about evil...

**Comment by noctuid** [comment]
There doesn't seem to be a cursor displayed in the company-box buffer even with evil. What is the problem this would address?

**Comment by Alexander-Miller** [comment]
It's definitely around for me. I've now removed it from the main window, but it's still visible  [in the scrollbar](https://imgur.com/a/O4GWwen).

**Comment by noctuid** [comment]
I think I can replicate that. Changing `cursor-in-non-selected-windows` to nil should be a sufficient fix though. I don't think there's a need to do anything specifically related to evil.

**Comment by Alexander-Miller** [comment]
Not everyone will want to change global settings to accommodate company-box. And it's not like the fix is all that complicated or expensive. It's just one trivial function and 1 or 2 well placed hooks to call it.

**Comment by noctuid** [comment]
I was suggesting setting it locally not globally.

**Comment by Alexander-Miller** [comment]
Ah, I thought it was a global variable. Never mind then.
