### ISSUE TITLE
lsp-mode no longer supports `company-lsp`

### ISSUE THREAD

**Issue by jsigman** [sebastiencs/company-box#143]
[LSP mode](https://github.com/emacs-lsp/lsp-mode/) no longer supports `company-lsp`, which is the only LSP backend supported by this package. Is it impossible to make this work with `company-capf`? This package looks awesome

**Comment by tshu-w** [comment]
@jsigman as far as I know, `lsp-mode` has preferred to use `company-capf` by default for a long time.

**Comment by jsigman** [comment]
Right on. Do you think there's a way to make this work with `company-capf`?

**Comment by tshu-w** [comment]
I didn't quite catch you, to make what work with `company-capf`

**Comment by jsigman** [comment]
`company-box`?

**Comment by tshu-w** [comment]
`company-box` does not conflict with `company-capf`, you just need enable `company-box-mode`

**Comment by jsigman** [comment]
From the README:

> For now, there are customs icons for 4 backends only: company-lsp, company-elisp, company-yasnippet and company-php.

The rich output of company-box is not enabled for `company-capf`, though... is this due to something fundamental in the way `company-lsp` works, compared to `company-capf`? My point is only that `company-lsp` is no longer an option if we want to use this package with LSP mode. 

By the way, thank you for prompt answering of questions. This mode looks cool and I would love to make it work with the latest LSP versions.

**Comment by nbfalcon** [comment]
Rich output works for me with `company-capf` and `lsp-completion-at-point`.

**Comment by MunsterPlop** [comment]
I can confirm it works for me out of the box as well.
