### ISSUE TITLE
tab line visible in gccemacs (28)

### ISSUE THREAD

**Issue by FelipeLema** [sebastiencs/company-box#149]
Compiled gccemacs against [b8d3ae78](http://git.savannah.gnu.org/cgit/emacs.git/commit/?h=feature/native-comp&id=b8d3ae78c54db7c7bb65d367a80f9be3d8744c48) I can see the Tab Line of company-box (see the picture below).

<img width="457" alt="tab-bar" src="https://user-images.githubusercontent.com/1232306/106334994-9ae9c880-626a-11eb-8424-c47803ab68d4.PNG">

Since you're reading this: thank y'all for maintaining such a useful and stable package

**Comment by sebastiencs** [comment]
Fixed with 79abd77f3357279c2726b74f8b20df27b71aa867
