### ISSUE TITLE
Got error when I enabled desktop-save-mode and restart Emacs from crash

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#16]
```
Company: frontend company-box-frontend error "Wrong type argument: frame-live-p, "Unprintable entity"" on command hide
Error running timer ‘company-idle-begin’: (error "Company: frontend company-box-frontend error \"Wrong type argument: frame-live-p, \"Unprintable entity\"\" on command hide")
```
I found ` (default-minibuffer-frame . "Unprintable entity")` and ` (company-box-buffer . "Unprintable entity")` in desktop-save file `(setq desktop-saved-frameset ...)`.

**Comment by dgutov** [comment]
> company-box-frontend

Need I say more?

**Comment by dgutov** [comment]
Never mind me, sorry. I thought this issue was in the company-mode repo. :flushed:

**Comment by larebsyed** [comment]
I am also facing this issue after enabling desktop save mode. What is the work around?

**Comment by sebastiencs** [comment]
Can you test the commit https://github.com/sebastiencs/company-box/commit/a8ce545670f72904ce16ee4d5ea3c478b2f48b9e ? It should solves the issue

**Comment by stardiviner** [comment]
Need to add one more `company-box-doc-frame` to `frameset-filter-alist`.

**Comment by stardiviner** [comment]
After some times testing, I found some entries still has `"unprintable entity"` in frameset.
Like: `company-box-buffer`, `company-box-buffer-origin`, `company-box-window`, `company-box-window-origin`, `company-box-scrollbar` etc and `default-minibuffer-frame`.
Don't know whether they are related. Like `company-box-buffer . "Unprintable entity"` exist in desktop save file, but seems does not affect `company-box`, does not report error.

**Comment by sebastiencs** [comment]
> Need to add one more company-box-doc-frame to frameset-filter-alist.

Done in https://github.com/sebastiencs/company-box/commit/51af281326a3af0ddd444a958c68dd5751849d37

If the others variables don't cause an error I think there is no need to add them to `frameset-filter-alist`, what do you think ?
