### ISSUE TITLE
company-box-limit error

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#17]
https://user-images.githubusercontent.com/378699/39458545-09d36400-4d28-11e8-8dfa-88003aa5b27f.png

`company-box-limit` does not work as `company-tooltip-limit`.
When `company-tooltip-limit` is `10`, and company-mode have `100` candidates. `company-tooltip` will show a scroll-bar. But `company-box` does not. and even I scroll down, `company-box` dismissed rest candidates. Only have `10` candidates. It suppose have `100` candidates and scroll-bar.

**Comment by sebastiencs** [comment]
It's fixed in https://github.com/sebastiencs/company-box/commit/25141e4501f3c345693d315c69fda2f5b925cc21

**Comment by stardiviner** [comment]
fix confirmed. Thanks @sebastiencs
