### ISSUE TITLE
icons-in-terminal not working

### ISSUE THREAD

**Issue by vijaypanchalr3** [sebastiencs/company-box#184]
i'm not good at elisp so i copied snippet from icons to fonts snipped. but it didn't work.

**Comment by Hi-Angel** [comment]
Amazing description. What exactly did you copy? Where did you copy it to? What did you snip? How exactly you expected it to work, and what actually happened?

Please post a minimal reproducible example, this report as it stands is useless for anybody you included.

**Comment by Hi-Angel** [comment]
> i'm not good at elisp

Btw, for your interest: these days you can use ChatGPT to help with that. It doesn't generate fully functioning code, in particular it misplaces parentheses in Emacs Lisp. But I would say, it does generate a prototype that you can debug and improve later on.

I myself used it to help migrating some code in a plugin I maintain from lists to hash-tables — saved some time in searching for the documentation, I only had to check the correctness regarding the functions it substituted and ofc to fix the parentheses.

**Comment by vijaypanchalr3** [comment]
Sorry @Hi-Angel , i was new at that time, and fascinated by this new way of interacting with contributors of projects you use and like. I was doing physics at that time so didn't had time for elisp. But i ensure you now that I'll not do this type of mistakes and waste other peoples valuable time. Sorry again.
