### ISSUE TITLE
Additionally remove company-pseudo-tooltip-frontend from company-frontends

### ISSUE THREAD

**Issue by noctuid** [sebastiencs/company-box#20]
company-tng, for example, adds `company-pseudo-tooltip-frontend` to `company-frontends`. Right now, company-box only deletes `company-pseudo-tooltip-unless-just-one-frontend` which causes issues since `company-pseudo-tooltip-frontend` is still in `companyf-frontends`. It may not be ideal, but company-childframe actually [advises `company-call-frontends`](https://github.com/tumashu/company-childframe/blob/fb799c3c8f8099a0ec7d21beb3b90136704c741e/company-childframe.el#L126) to remove both `company-pseudo-tooltip-frontend` and `company-pusedo-tooltip-unless-just-one-front-end`. For now, I'm just additionally deleting `company-pseudo-tooltip-frontend` from `company-frontends` in my config after loading company-tng.

**Comment by sebastiencs** [comment]
Thanks, it's done in https://github.com/sebastiencs/company-box/commit/32f9951250669ab715a38b8382257204852ee35d

**Comment by noctuid** [comment]
Thanks.
