### ISSUE TITLE
display company-box child-frame height based on font size

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#21]
![image](https://user-images.githubusercontent.com/378699/39674397-e7921fd0-517d-11e8-9f18-1dab06477ab6.png)
You can see the third candidate is not fully displayed. 
Don't know whether company-box child-frame can display based on company-box child-frame font size.

Here is my config changed company-box frame font:
```elisp
(add-to-list 'company-box-frame-parameters
               '(font . "-SRC-Hack-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1"))
  (add-to-list 'company-box-frame-parameters
               '(font-parameter . "-SRC-Hack-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1"))
```

**Comment by nealot** [comment]
I think your icons are larger than your candidates in size.

**Comment by sebastiencs** [comment]
The height is already based on the font size of the frame.
I think you have this because of the icons you're using. They are bigger than the default font. Try to make the icons smaller ?

**Comment by stardiviner** [comment]
@sebastiencs You're right. I make it smallerer (0.7) (eve I already did that smaller 0.8~0.9). It works fine now.
