### ISSUE TITLE
Icons are very large

### ISSUE THREAD

**Issue by barcharcraz** [sebastiencs/company-box#38]
![screenshot from 2018-06-07 11-31-33](https://user-images.githubusercontent.com/1304509/41110187-c7b61b08-6a46-11e8-8408-a07eea9c7c1c.png)

My I don't think my configuration is anything special. I do use variable width text for almost all faces though (which is one reason I'm very interested in company-box

**Comment by barcharcraz** [comment]
Also my emacs configuration is at https://github.com/barcharcraz/emacsfiles

**Comment by nlamirault** [comment]
Same for me.
![2018-06-12-133731_438x304_scrot](https://user-images.githubusercontent.com/29233/41288197-cc420cce-6e45-11e8-9ba8-dc96c2cea8c5.png)

**Comment by Atman50** [comment]
I have the same problem with company-lsp and company-box:
![emacs](https://user-images.githubusercontent.com/3370807/42760020-ef176a9a-88d6-11e8-93ae-67e9873f20fb.JPG)

**Comment by Alexander-Miller** [comment]
As I've learned in treemacs resizing icons on the fly is in fact quite simple. All you need to do is recreate them with a call like `(create-image file-path 'imagemagick nil :ascent 'center :width width :height height)`.

**Comment by azzamsa** [comment]
Do we have solution for this ?

**Comment by seagle0128** [comment]
Same issue here. Any update?

**Comment by vv111y** [comment]
I shrank mine by 50% both WxH, which makes them 1/4 size. Looks just right.   

You probably want a function so it is easy to adjust anytime.

**Comment by seagle0128** [comment]
@vv111y Can you share your method here?

**Comment by vv111y** [comment]
I did this from the shell. For myself, the image folder was located at

```~/.emacs.d/elpa/26.1/develop/company-box-20180607.1545/images```

then I entered 

```mogrify -resize 50% *.png```

You can use ```file *``` before and after to see the size differences. I needed to restart emacs after that.

**Comment by dsvensson** [comment]
Maybe there's some font icons in the `all-the-icons` package, that would automatically scale?

**Comment by seagle0128** [comment]
@dsvensson  I can approve `all-the-icons` works perfectly with `company-box`. PR #2 is not perfect.

**Comment by seagle0128** [comment]
PR #42 has been merged. And my enhancement is on https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-company.el#L76.
