### ISSUE TITLE
[feature request] Add support for "common-face"

### ISSUE THREAD

**Issue by casouri** [sebastiencs/company-box#43]
In company you can set different faces for "common" part of the candidates as your input:

<img width="443" alt="screen shot 2018-07-05 at 12 51 48 pm" src="https://user-images.githubusercontent.com/13118647/42303174-3ed6b500-8052-11e8-9c07-f7c2a3fafbeb.png">

Notice the purple and blue faces.

The faces are `company-tooltip-common` and `company-tooltip-common-selection`.

It would be cool if company-box can support these too.

**Comment by Yevgnen** [comment]
I miss this face too!

**Comment by seagle0128** [comment]
Any update for this feature?

**Comment by sebastiencs** [comment]
Closing, it's been implemented in https://github.com/sebastiencs/company-box/pull/56
