### ISSUE TITLE
Search face is missing in `company-filter-candidates`

### ISSUE THREAD

**Issue by Yevgnen** [sebastiencs/company-box#46]
Hi, thanks for the awesome package.

When I doing `company-filter-candidates`, the face `company-tooltip-search` is missing. Is this a bug?

By the way, can I disable the scrollbar completely? 

Thanks in advance.

**Comment by seagle0128** [comment]
It seems duplicated with #12 .

**Comment by sebastiencs** [comment]
Fixed with https://github.com/sebastiencs/company-box/commit/1ff1297dd03eb4ede7dfde509d7e4235e00b2f63
