### ISSUE TITLE
desktop-save-mode integration: it should ignore company-box buffers/windows

### ISSUE THREAD

**Issue by edkolev** [sebastiencs/company-box#49]
Hi, and thanks for this package!

I'm using desktop-save-mode which is meant to save parts of emacs (e.g. buffers, windows, variables) on emacs start. It incorrectly restores company-box windows. Here's a screenshot of a fresh emacs that has company-box windows/buffers revived from the previous session:

![screen shot 2018-07-18 at 07 28 58](https://user-images.githubusercontent.com/1532071/42859920-82453d06-8a5d-11e8-9148-ec71d8f11d87.png)

The fix should be a simple one - desktop-save-mode has to be configured to ignore company-box windows/buffers. I'll post here if I find a fix.

**Comment by tam5** [comment]
My solution / workaround:

```
(defun delete-company-box-frame ()
  "Delete the company box frame."
  (if (framep (company-box--get-frame))
      (delete-frame (company-box--get-frame))))

(add-hook 'desktop-save-hook 'delete-company-box-frame)
```

**Comment by seagle0128** [comment]
Another solution/workaround:

```elisp
(push '(company-box-mode . nil)
      desktop-minor-mode-table)
```
