### ISSUE TITLE
Icons should all be the same size

### ISSUE THREAD

**Issue by Alexander-Miller** [sebastiencs/company-box#50]
Otherwise there's ugly misalignment: https://imgur.com/a/QdshJe3

When this is assured I also have plans for PRs  to 
 1. ensure that line height in company-box will take the height of icons into account (also visible in the  picture, only half of the last line is visible).
 2. add an option to resize icons interactively

**Comment by cmatzenbach** [comment]
I only have this issue in php-mode.  I'm not sure why that is, but it looks exactly the same.  +1

**Comment by seagle0128** [comment]
Same issue here. Too large...

**Comment by hkjels** [comment]
Still an issue
`sips --resampleWidth 16 ./images/*` <- made it look a little nicer, but also a little blurred off-course

**Comment by sebastiencs** [comment]
Does it still occur after https://github.com/sebastiencs/company-box/pull/82 ?

**Comment by Alexander-Miller** [comment]
Yes, it does. The icons' type must be set to `imagemagick` instead of `png`  for the sizing to work.

**Comment by sebastiencs** [comment]
@Alexander-Miller thanks. I added `imagemagick` in https://github.com/sebastiencs/company-box/commit/9a39b820796453b852b172de320d01be913c6f96

**Comment by hkjels** [comment]
I was using the version on melpa which didn't have the imagemagick line. I now switched to the latest version, but then icons disappeared entirely. `company-box--have-imagemagick` returns `t`

**Comment by sebastiencs** [comment]
@hkjels Does `(image-type-available-p 'imagemagick)` returns `t` as well ?

**Comment by hkjels** [comment]
yup

**Comment by sebastiencs** [comment]
@Alexander-Miller Any idea why the images don't appear ?

**Comment by Alexander-Miller** [comment]
Nope.

@hkjels What does your `company-box-icons-images` look like? What happens when you `(insert (propertize " " 'display (alist-get 'Method company-box-icons-images)))`?

**Comment by hkjels** [comment]
Ahh.. Figured it out
Looks like a `straight.el` issue. It's looking for the images where `straight.el` keeps the build, whereas the images are only in the downloaded repo. Copying the images directory to the build-directory worked wonders

**Comment by sebastiencs** [comment]
@hkjels Do the images have the same size now ?

**Comment by Alexander-Miller** [comment]
I use straight.el as well and I have no such problem - the images are in the build directory. Sounds like a blooper happened somewhere.

**Comment by seagle0128** [comment]
It does work well now. Thanks!

**Comment by hkjels** [comment]
It's properly sized now. Slightly off on vertical alignment, but that I can live with. Thanks for helping!

**Comment by hkjels** [comment]
> I use straight.el as well and I have no such problem - the images are in the build directory. Sounds like a blooper happened somewhere.

Interesting. I tried removing the package and re-installing, but to no avail. I have to copy them manually

**Comment by sebastiencs** [comment]
@hkjels Great, thanks for your confirmation

@Alexander-Miller Does it work for you too ? Can this issue be close ?

**Comment by Alexander-Miller** [comment]
It's working fine on my end.
