### ISSUE TITLE
The C-v and M-v to scroll page in company-box tooltip does not work.

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#58]
When I use `[C-v]` or `[M-v]` to scroll page in company-box tooltip. It does not work correctly, I saw scrollbar scrolled, but the candidates are not scrolled.

**Comment by stardiviner** [comment]
This issue happens on company candidates searching/filtering too.

**Comment by stardiviner** [comment]
I searched company-box functions, seems does not support searching nor filtering.

**Comment by stardiviner** [comment]
@sebastiencs gentle ping ....

**Comment by drfiresign** [comment]
I am also having this issue on my end. any assistance would be greatly appreciated.

**Comment by bcclaywell** [comment]
I was able to work around this issue with the following key remaps:

```
(define-key company-active-map (kbd "M-v") (lambda ()
                                             (interactive)
                                             (company-previous-page)
                                             (company-box--change-line)
                                             ))
(define-key company-active-map (kbd "C-v") (lambda ()
                                             (interactive)
                                             (company-next-page)
                                             (company-box--change-line)
                                             ))
```

**Comment by drfiresign** [comment]
@bcclaywell THANK YOU! This is awesome, I really appreciate your following up.

**Comment by stardiviner** [comment]
With this hint, I use this advice solved problem.
```elisp
  (advice-add 'company-next-page :after #'company-box--change-line)
  (advice-add 'company-previous-page :after #'company-box--change-line)
  (advice-add 'company-search-candidates :after #'company-box--change-line)
  (advice-add 'company-filter-candidates :after #'company-box--change-line)
  (advice-add 'company-search-repeat-forward :after #'company-box--change-line)
  (advice-add 'company-search-repeat-backward :after #'company-box--change-line)
```

**Comment by ericdallo** [comment]
Great workaround, thanks @stardiviner!

**Comment by mpereira** [comment]
The workaround provided by @stardiviner seems to not work in recent versions of company-box. I'm trying to figure out a fix.

**Comment by mpereira** [comment]
Using `company-box--move-selection` instead of `company-box--change-line` seems to do the trick:
```emacs-lisp
(advice-add 'company-next-page :after #'company-box--move-selection)
(advice-add 'company-previous-page :after #'company-box--move-selection)
(advice-add 'company-search-candidates :after #'company-box--move-selection)
(advice-add 'company-filter-candidates :after #'company-box--move-selection)
(advice-add 'company-search-repeat-forward :after #'company-box--move-selection)
(advice-add 'company-search-repeat-backward :after #'company-box--move-selection)
```

**Comment by sebastiencs** [comment]
@mpereira With latest versions of `company-box`, those advice-add are not needed anymore.
https://github.com/sebastiencs/company-box/pull/119 removed the keymap of company-box and now it relies on the exact same keymap than the "normal" `company-mode`.

Can you try without those advice-add and let me know if you have any issues.
Thanks

**Comment by mpereira** [comment]
@sebastiencs I just confirmed that `company-next-page` and `company-previoust-page` work nicely without the advices, thanks!

I'm not sure if it's my configuration, but it seems that `company-filter-candidates` isn't working as expected with the latest company-box. Disabling company-box makes it work as expected (candidates are filtered to the input). Would you be able to test it there?

FWIW, I use this keybinding for triggering `company-filter-candidates`:

```emacs-lisp
(general-define-key
 :keymaps '(company-active-map)
 "C-/" 'company-filter-candidates)
```

macOS Catalina
Emacs: 28.0.50
company-box: 20200904.533

**Comment by sebastiencs** [comment]
@mpereira I just tested and yes it doesn't work. I will fix that

**Comment by sebastiencs** [comment]
@mpereira This should be fixed with https://github.com/sebastiencs/company-box/commit/2cc7d907382f7c3325663d4aecb5ef760e88fdf0

**Comment by mpereira** [comment]
@sebastiencs works great now, thanks for fixing it so quickly!
