### ISSUE TITLE
Flash issue in fullscreen

### ISSUE THREAD

**Issue by seagle0128** [sebastiencs/company-box#59]
When using Emacs in fullscreen mode on macOS Mojave, flash issue happens. Disable `company-box-mode`, it works again.

- Emacs 26.1
- macOS Mojave
- company-box-20180607.1545

**Comment by ArchCST** [comment]
Same issues here

**Comment by sebastiencs** [comment]
@seagle0128 Could you provide a video/gif of the issue ?

**Comment by seagle0128** [comment]
Attached the recording.
[Screen Recording 2019-01-22 at 9.03.33 PM-iphonepod.mp4.zip](https://github.com/sebastiencs/company-box/files/2782884/Screen.Recording.2019-01-22.at.9.03.33.PM-iphonepod.mp4.zip)

**Comment by seagle0128** [comment]
I think it's related to child frame.

**Comment by seagle0128** [comment]
I don't think this issue can be fixed in `company-box` since it's an issue of Emacs.
The workaround it not using native fullscreen mode in macOS.

```elisp
(setq ns-use-native-fullscreen nil)
```
