### ISSUE TITLE
images folder through melpa missing

### ISSUE THREAD

**Issue by technician77** [sebastiencs/company-box#6]
When I installed company-box through melpa I got errors that images were missing. Turned out the whole images folder was not in the package folder. After copying it manually from github everything works fine. I don't know much about melpa. I just know some packages seem to come with "extra" content and some download it via curl or something on first run. You might look into the issue I assume it's easy to fix.

**Comment by sebastiencs** [comment]
Thank you, I just made a PR to fix that: https://github.com/melpa/melpa/pull/5422

**Comment by technician77** [comment]
Yes, but you already have seen that the #5 is not related and fixed it.

Regarding the images folder it seems that the latest melpa is still missing the images folder or it is missing it again.

**Comment by sebastiencs** [comment]
@technician77 Yes we need to wait for the PR on melpa to be merged

**Comment by sebastiencs** [comment]
@technician77 The package on melpa now contains the image folder :)
