### ISSUE TITLE
make company-box-doc tooltip aware screen boarder

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#61]
`company-box-doc` should be smart to aware screen boarder. Like in bellowing screenshot, it should shown on another side screen space:

![company-box-doc output screen boarder](https://user-images.githubusercontent.com/378699/51674953-322d3d00-200d-11e9-9bf0-45203d52cc14.png)

![image](https://user-images.githubusercontent.com/378699/53801317-d1811080-3f79-11e9-8296-20065512251d.png)

**Comment by stardiviner** [comment]
Any idea or solution for this?

**Comment by stardiviner** [comment]
Gentle ping ...

**Comment by sebastiencs** [comment]
@stardiviner See https://github.com/sebastiencs/company-box/issues/29#issuecomment-395355582

> It is supposed to be on the left when there isn't enough space on the right

Moving the doc on top or bottom of the completion frame is not yet implemented but it's on my todo list

**Comment by stardiviner** [comment]
This is implemented, so closed now. Thanks @sebastiencs
