### ISSUE TITLE
mac os x - company box incompatible with full screen

### ISSUE THREAD

**Issue by vidjuheffex** [sebastiencs/company-box#67]
Upon the opening of the box itself. A box appears in the center of the screen, then it snaps into place. However the title bar is no longer accesible, moving the mouse up to the top shifts you over to left, to a new, all-black, screen.

![ezgif-1-e7e929faf476](https://user-images.githubusercontent.com/3157835/60316139-06511300-992f-11e9-83ba-394ef3d712ea.gif)

This gif doesn't capture it super well (the app crashes I think because on top of that I had video capture running) usually it doesnt crash, I just end up with an black screen, and I cant access the top bar by bringing my mouse near the top.

**Comment by muffinmad** [comment]
@vidjuheffex It's not the `company-box` issue but NS port of Emacs. Same issue with all packages that create child frame. Check out Emacs Mac port - this issue is [fixed](https://bitbucket.org/mituharu/emacs-mac/src/master/NEWS-mac) in emacs-26.2-mac-7.6 version.

**Comment by vidjuheffex** [comment]
Thanks @muffinmad

**Comment by muffinmad** [comment]
This issue is [fixed in NS port of Emacs 28 now](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=bbc48b263485c26c6823eabdbbd7e9af62178e34)

**Comment by ashton314** [comment]
Seems to be an issue in 27.1 on macOS Catalina as of 2020-08-14. Anyone else seeing this as well?

**Comment by muffinmad** [comment]
@ashton314 Yes, Emacs 27.1 doesn't contain the patch. It's installed on Emacs 28.
