### ISSUE TITLE
Compilation fails and company breaks with latest Emacs

### ISSUE THREAD

**Issue by brainplot** [sebastiencs/company-box#75]
Hi, I'm trying to install `company-box` from the MELPA repository using `package-install` and, during compilation, a new window opens up with the following message:
```
Leaving directory ‘/home/gianluca/.emacs.d/elpa/company-box-20190311.1745’

Compiling file /home/gianluca/.emacs.d/elpa/company-box-20190311.1745/company-box-doc.el at Sat Nov 23 22:19:23 2019
Entering directory ‘/home/gianluca/.emacs.d/elpa/company-box-20190311.1745/’
company-box-doc.el:44:1:Warning: defcustom for ‘company-box-doc-delay’ fails
    to specify type
company-box-doc.el:44:1:Warning: defcustom for ‘company-box-doc-delay’ fails
    to specify type

In end of data:
company-box-doc.el:152:1:Warning: the function ‘string-trim’ is not known to
    be defined.

Compiling file /home/gianluca/.emacs.d/elpa/company-box-20190311.1745/company-box-icons.el at Sat Nov 23 22:19:23 2019
company-box-icons.el:134:10:Error: Symbol’s function definition is void: all-the-icons-faicon

Compiling file /home/gianluca/.emacs.d/elpa/company-box-20190311.1745/company-box.el at Sat Nov 23 22:19:23 2019

In end of data:
company-box.el:730:1:Warning: the following functions are not known to be defined:
    icons-in-terminal, string-trim
```
Trying to use the package despite the compilation errors results in `company` no longer working, as in [this video](https://imgur.com/WtPezig) I recorded. Technically tab-complete works fine, as shown in the video, but I don't get the pop-up with the list of members to choose from.
When I try to manually bring up `company` via the `company-complete` command I get the following message:
```
Company: frontend company-box-frontend error "Symbol’s function definition is void: string-trim" on command update
```
Deleting `company-box` (or avoiding to load it up as a minor mode) makes `company-mode` pop-ups work again as normal.

### System Info
```bash
$ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
```bash
$ uname -a
Linux mars 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux
```
```bash
$ cat /etc/*release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**Comment by dgutov** [comment]
> Symbol’s function definition is void: string-trim

Sounds like you need (it needs): `(require 'subr-x)`.

**Comment by brainplot** [comment]
So as a workaround I should be able to get it working by placing `(require 'subr-x)` in one of my init files before loading `company-box`, but in theory that should've been in the source code. Is that correct?

**Comment by dgutov** [comment]
That's right.

**Comment by brainplot** [comment]
Tried that but I get a different error when compiling:
```
Leaving directory ‘/home/gianluca/.emacs.d/elpa/company-box-20190311.1745’

Compiling file /home/gianluca/.emacs.d/elpa/company-box-20190311.1745/company-box-doc.el at Sun Nov 24 01:17:49 2019
Entering directory ‘/home/gianluca/.emacs.d/elpa/company-box-20190311.1745/’
company-box-doc.el:44:1:Warning: defcustom for ‘company-box-doc-delay’ fails
    to specify type
company-box-doc.el:44:1:Warning: defcustom for ‘company-box-doc-delay’ fails
    to specify type

Compiling file /home/gianluca/.emacs.d/elpa/company-box-20190311.1745/company-box-icons.el at Sun Nov 24 01:17:49 2019
company-box-icons.el:134:10:Error: Symbol’s function definition is void: all-the-icons-faicon

Compiling file /home/gianluca/.emacs.d/elpa/company-box-20190311.1745/company-box.el at Sun Nov 24 01:17:49 2019

In end of data:
company-box.el:730:1:Warning: the function ‘icons-in-terminal’ is not known to
    be defined.
```
Looks like this package needs the `all-the-icons` package, which I don't have installed, even though it's not specified in the `README.md`. `company-box` doesn't seem to pull it down as a dependency either.

**Comment by dakra** [comment]
those are only warnings and can be ignored.
but jFYI, I was annoyed by the compiler warnings as well and made a while ago a branch with company-all-the-icons stuff separated in it's own package.
https://github.com/dakra/company-box/tree/fix-missing-all-the-icons

**Comment by brainplot** [comment]
It doesn't look like a warning to me. It says it's an error and it's also highlighted as red, unlike the other warnings which are yellow :thinking: 

![Screenshot_20191124_151252](https://user-images.githubusercontent.com/28014843/69495994-8aeb9180-0ecd-11ea-859a-0bc3461862e9.png)

After applying the workaround as per @dgutov's suggestion, now company pop-ups do show up but the whole thing doesn't quite work as intended. If I keep pressing arrow down to cycle through the available suggestions, the "view" doesn't follow my selection like it used to. [I recorded a video](https://imgur.com/d7lFSB7) to better show what I'm talking about.

This is the code relevant to `company-box` in my init file:
```elisp
(require 'subr-x)
(use-package company-box
  :hook (company-mode . company-box-mode))
```

**Comment by dgutov** [comment]
"faicon"? Someone clearly made a typo somewhere.

**Comment by brainplot** [comment]
I'm on mobile right now but it should be easy enough to spot with something like `grep`.

**Comment by cloudrck** [comment]
> "faicon"? Someone clearly made a typo somewhere.

That's the name for [**F**ont **A**wesome **Icon** Function](https://github.com/domtronn/all-the-icons.el/blob/0b74fc361817e885580c3f3408079f949f5830e1/all-the-icons.el#L72).

@brainplot did you ever figure this issue out? I'm having the same issue, going to have to have to take a look.

**Comment by brainplot** [comment]
Sadly, no I didn't. I just uninstalled the plugin. It wasn't something that improves my productivity so I didn't mind too much :slightly_smiling_face:

**Comment by sebastiencs** [comment]
Hi @brainplot, those warnings should be fixed

**Comment by sebastiencs** [comment]
@brainplot I'm closing the issue. Feel free to reopen if it still occurs
