### ISSUE TITLE
Poor rendering of popup

### ISSUE THREAD

**Issue by rynoV** [sebastiencs/company-box#76]
When company-box is enabled the popup frequently renders strangely:
![image](https://user-images.githubusercontent.com/35615725/70402247-febe8b80-19ef-11ea-9688-90f5405af011.png)
![image](https://user-images.githubusercontent.com/35615725/70402258-0847f380-19f0-11ea-9f20-666ba76c3653.png)
![image](https://user-images.githubusercontent.com/35615725/70402261-0a11b700-19f0-11ea-864d-509a1e36174b.png)
After about four characters into a word it starts to render normally again, and sometimes it renders normally from the start.
My Company version is 0.9.10 and my Emacs is 26.3. I'm using the GUI Emacs through VcXsrv on Windows Subsystem Linux. Any ideas on how to fix this?

**Comment by dgutov** [comment]
Do you see the same problem with `company-posframe`? If so, it might be a bug with child frames, and the report should go into Emacs core.

**Comment by rynoV** [comment]
With `company-posframe` and `company-box` it's not as bad but still some issues:
![image](https://user-images.githubusercontent.com/35615725/70450524-1e41cc80-1a61-11ea-95d9-504fd2f6f769.png)
![image](https://user-images.githubusercontent.com/35615725/70450536-24d04400-1a61-11ea-946a-7aa24185940b.png)
I don't see the white or the static-y parts with `company-posframe`, maybe that was a child frame bug?

**Comment by dgutov** [comment]
Both packages use a child frame. But it could still be an Emacs bug, just manifesting differently.

Try asking the postframe's author, though. Maybe it's just HiDPI related, and something each package needs to deal with.

**Comment by dgutov** [comment]
(I have a HiDPI screen, and I've noticed some problems with rendering as well)

**Comment by minikN** [comment]
I'm having similar issues with company-box.

I've created a minimal setup to be sure nothing in my config is causing this.

init.el:
```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     	     '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(unless (package-installed-p 'use-package)
    (package-refresh-contents)

   (package-install 'use-package))

(add-hook 'compan

(use-package company
  :ensure t
  :hook (after-init-hook . global-company-mode))

(use-package company-box
  :ensure t
  :hook (company-mode . company-box-mode))
```

And this is how company-box looks:

![image](https://user-images.githubusercontent.com/1888338/71015312-ac6a2280-20f3-11ea-8911-49629ec16431.png)
![image](https://user-images.githubusercontent.com/1888338/71015380-c9065a80-20f3-11ea-9dc1-271888ed6718.png)
![image](https://user-images.githubusercontent.com/1888338/71015418-da4f6700-20f3-11ea-934e-596cd4d0e645.png)
![image](https://user-images.githubusercontent.com/1888338/71015503-ff43da00-20f3-11ea-869f-957fb0d4e6a4.png)
![image](https://user-images.githubusercontent.com/1888338/71017196-85f9b680-20f6-11ea-8516-099bc01b6fc0.png)


Your imagination is the limit - everything is possible, basically.

Couple of question:
 - Why is the margin between the icons and the text so small?
 - Why seem some help boxes deattached from the box? I've had help information popping up in every corner of the screen
 - What is the black?
```
emacs --version
GNU Emacs 26.3
```
company-box version: 0.0.1

**Comment by minikN** [comment]
I have to apologize. I was actually not using a minimal config like I said before. I think I found the answer to (at least) the black spots in my pictures.

`(tool-bar-mode -1)` .. for whatever reason is causing that. If I remove that statement the boxes are being diplayed correctly. I hope that is helpful.

**Comment by dgutov** [comment]
@minikN Does that fix all the artefacts? If so, it's definitely something to `M-x report-emacs-bug` about.

**Comment by minikN** [comment]
> @minikN Does that fix all the artefacts? If so, it's definitely something to `M-x report-emacs-bug` about.

Yes and no. I have no artifacts on the help boxes (sorry, I don't know their name) with `tool-bar-mode -1`.

However, after digging a bit further. I also have problems with the scroll bar. I've created two gifs to showcase the problem.

All recordings are with `(tool-bar-mode -1)`. In addition the first one is with `(scroll-bar-mode -1)`, the second with `(scroll-bar-mode 1)`:
![add-hook](https://user-images.githubusercontent.com/1888338/71090149-a2532d00-21a2-11ea-9422-be33b296ff73.gif)

Notice the black artifact here, and also the scrollbar popping in place:
![add-hook2](https://user-images.githubusercontent.com/1888338/71090177-b860ed80-21a2-11ea-818f-a6fb560eb2ae.gif)

**Comment by minikN** [comment]
@rynoV Can you verify my hypothesis regarding `tool-bar-mode -1`?

**Comment by minikN** [comment]
Sorry for spamming the issue, but @dgutov, would you be able to answer some questions regarding `company-box`
 - Is it possible to increase the space between the icons and the text?
 - Is it possible to either decrease the width of the scroll bar or hide it completely - but without having a space between the popup and the information box (see gif above)?

Thanks.

**Comment by dgutov** [comment]
* I'm not the author, not I do use it. If there are relevant options, try changing them. Otherwise, of course, it should be possible to change in the implementation.
* This still looks like a bug, but not sure in which component exactly.

**Comment by minikN** [comment]
> * I'm not the author, not I do use it. If there are relevant options, try changing them. Otherwise, of course, it should be possible to change in the implementation.
> * This still looks like a bug, but not sure in which component exactly.

Sorry, I knew you weren't the author, this was suppose to be referred to @sebastiencs. Got confused a little.

**Comment by minikN** [comment]
Regarding the icon-text space: https://github.com/sebastiencs/company-box/pull/77

For anyone interested.

**Comment by rynoV** [comment]
> @rynoV Can you verify my hypothesis regarding `tool-bar-mode -1`?

Changing `tool-bar-mode` doesn't seem to change anything for me.

**Comment by minikN** [comment]
> > @rynoV Can you verify my hypothesis regarding `tool-bar-mode -1`?
> 
> Changing `tool-bar-mode` doesn't seem to change anything for me.

That's very unfortunate. Did you change it to `tool-bar-mode 1`?

**Comment by minikN** [comment]
> > > @rynoV Can you verify my hypothesis regarding `tool-bar-mode -1`?
> > 
> > 
> > Changing `tool-bar-mode` doesn't seem to change anything for me.
> 
> That's very unfortunate. Did you change it to `tool-bar-mode 1` or comment it out?

**Comment by rynoV** [comment]
> Did you change it to tool-bar-mode 1 or comment it out?

I executed `(tool-bar-mode 1)` and `(tool-bar-mode -1)` and didn't see any change.
> Might also be the case that the artifacts you are seeing are caused by `scroll-bar-mode`

I did the same with `scroll-bar-mode` and that didn't change anything either.

**Comment by minikN** [comment]
Alright @rynoV @dgutov,

after still struggling with this. I've finally found a solution (Playing with `tool-bar-mode` and `scroll-bar-mode` didn't fix it for me as well after all).

The problem is not `company-box` nor `emacs`. It's `VcXsrv`, specifially it's implemetation of GLX. A more detailed description can be found [here](https://sourceforge.net/p/vcxsrv/bugs/102/).

The solution is to switch to another x server (`Xming` causes the same problems). I' currently trying out `MobaXTerm` which does not have this issue. However there might be better alternatives out there, I'm just scratching the surface.

However it's good that the culprit has been identified.

**Comment by rynoV** [comment]
Switching to MobaXTerm does fix this issue for me, thanks @minikN.
