### ISSUE TITLE
Company-box flickers with every keystroke

### ISSUE THREAD

**Issue by ianpan870102** [sebastiencs/company-box#79]
First of all, thank you for this package, it adds visual-pleasing icons to spark up the tooltip, and also solves the issue of company-mode partially hiding the diaplay-line-number.

However, I notice small flickers of the tooltips on every keystroke, as the drop-down re-renders the candidates. The flickers have nothing to do with company-box-doc, since I've disabled it from the start. 

I wonder if there's a solution for this, or if Emacs just has poorer support for childframe rendering compared to other modern editors. Cheers.

**Comment by dgutov** [comment]
It does flicker, depending on WM, apparently.

We touched on this problem on emacs-devel, see https://lists.gnu.org/archive/html/emacs-devel/2020-01/msg00515.html. You can join in that discussion with your observations, or file a bug report too.

**Comment by ianpan870102** [comment]
I see. For the record, I'm on macOS Catalina with emacs-plus --HEAD (v28.0.50)

**Comment by dgutov** [comment]
> I'm on macOS Catalina with emacs-plus --HEAD (v28.0.50)

That's some useful info for a bug report.

I'm on GNOME 3.32 myself.

**Comment by dgutov** [comment]
@ianpan870102 BTW, have you tried https://github.com/tumashu/company-posframe/?

It doesn't use icons, but has some other extra features.

**Comment by ianpan870102** [comment]
@dgutov Yes, I've tried the company-posframe approach, but the flickering issue remains (and seems to be more severe than company-box(?)). Actually I don't care too much about the icons either, my main purpose was for the tooltip to not interfere/hide the displayed line-numbers on the editor left hand side, as this is a long-standing issue for company-mode.

**Comment by dgutov** [comment]
Interesting. company-posframe works more reliably on my machine.

Someone should look into their implementations' differences and merge the best parts, or something.

**Comment by ericdallo** [comment]
For me, this was resolved using `(setq company-box-doc-enable nil)` on NixOS - Gnome 3.34, Emacs 26.3

**Comment by ianpan870102** [comment]
I'm currently on a WSL2+Windows10 machine, and this flickering issue doesn't exist anymore. I suppose it has to do with macOS support after all. Closing this issue as it doesn't seem to be the scope of this package.
