### ISSUE TITLE
company-box seems to have stopped working after latest update

### ISSUE THREAD

**Issue by joostkremers** [sebastiencs/company-box#86]
After updating the package yesterday, `company-box` seems to have stopped working altogether. No box pops up anywhere anymore...

I'm not sure where I should begin trying to debug this. `company-frontends` includes `company-box-frontend` (at least buffer-locally), I don't know what else is needed for a proper functioning `company-box`. There's nothing in `*Messages*` that looks relevant and I don't seem to be getting any other errors.

Is there some place I should be looking for errors? Is there some function I could edebug to figure out what's going on?

**Comment by joostkremers** [comment]
PS: my keyboard went haywire, which caused me to post an empty issue... My apologies, I updated the issue just now.

**Comment by Daskeladden** [comment]
@joostkremers Works for me, most likely something in your init?

There was an update to the function `company-box--update-line`, perhaps you call this (or redefine it) in your own configuration?

**Comment by joostkremers** [comment]
> @joostkremers Works for me, most likely something in your init?

Apparently... I actually added the `org-roam` and `company-org-roam` packages to my config yesterday and as it turns out, the latter is the culprit. If I disable it, everything starts working again.

Sorry for the noise, I should have checked that first, obviously...
