### ISSUE TITLE
tab-line-mode affects box placement

### ISSUE THREAD

**Issue by cwhatley** [sebastiencs/company-box#89]
When I have global-tab-line-mode off, the placement of the menu is generally correct across the modes I tested, but when it is turned on, the company box is off by the height of the tab line which leads to the cursor location being covered over by the menu box.

No tab line:

![image](https://user-images.githubusercontent.com/573757/81444901-f5c01a80-9145-11ea-8dc9-eb7db5577873.png)

With tab line activated:

![image](https://user-images.githubusercontent.com/573757/81444939-07092700-9146-11ea-88b0-fc44c9d9aac6.png)

Cursor is in the same spot in both.

**Comment by sebastiencs** [comment]
Hi @cwhatley , it should be fixed with https://github.com/sebastiencs/company-box/commit/17f20bf11377a0dd75d1c918095a5d7ae980cb92

**Comment by cwhatley** [comment]
Excellent!

**Comment by CsBigDataHub** [comment]
@sebastiencs 

#17f20bf is breaking company box.

I am getting the error below

```error
Company: An error occurred in auto-begin
Company: frontend company-box-frontend error "Symbol’s function definition is void: window-tab-line-height" on command update

```

**Comment by gilbertwong96** [comment]
I have encountered the same error, @CsBigDataHub.  Could you please merge this pull request ? https://github.com/sebastiencs/company-box/pull/90/files @cwhatley

**Comment by sebastiencs** [comment]
@CsBigDataHub @gilbertwong96 The PR to fix this bug has been merged

**Comment by CsBigDataHub** [comment]
Thanks @sebastiencs
